# Generated by Django 5.1.3 on 2024-11-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurationPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=254)),
                ('restauration_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('frige', 'Réfrégirateur')], max_length=25)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('status', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('photo_link', models.ImageField(null=True, upload_to='')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
