# Generated by Django 5.1.4 on 2025-01-09 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='establishment',
            new_name='id_establishment',
        ),
    ]
