# Generated by Django 5.1.3 on 2024-12-05 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chillzone', '0002_alter_restaurationplace_photo_link_etablishment_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMeta',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('validated', 'Validé'), ('blocked', 'Bloqué'), ('banned', 'Banni')], max_length=24)),
                ('verified', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('photo_link', models.ImageField(blank=True, upload_to='')),
                ('establishment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chillzone.etablishment')),
            ],
            options={
                'db_table': 'auth_user_meta',
            },
        ),
    ]
