# Generated by Django 5.1.4 on 2025-01-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0003_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurationplace',
            name='restauration_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('fridge', 'Réfrégirateur')], max_length=25),
        ),
    ]
