# Generated by Django 5.1.3 on 2024-12-05 23:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0003_usermeta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Etablishment',
            new_name='Establishment',
        ),
        migrations.AddField(
            model_name='usermeta',
            name='role',
            field=models.CharField(default='Etudiant', max_length=254),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
