# Generated by Django 5.1.4 on 2025-01-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0004_alter_restaurationplace_restauration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='photo_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
