# Generated by Django 5.1.4 on 2024-12-17 14:28
# To reload my mistake 

from django.db import migrations

def delete_tables(apps, schema_editor):

    # Suppression des tables
    schema_editor.execute("""
        DROP TABLE IF EXISTS chillzone_category;
        DROP TABLE IF EXISTS chillzone_location;
        DROP TABLE IF EXISTS chillzone_notification;
        DROP TABLE IF EXISTS chillzone_tag;
        DROP TABLE IF EXISTS chillzone_tagcategory;
        DROP TABLE IF EXISTS chillzone_calendar;
        DROP TABLE IF EXISTS chillzone_associate;
        DROP TABLE IF EXISTS chillzone_command;
        DROP TABLE IF EXISTS chillzone_commandcomposition;
        DROP TABLE IF EXISTS chillzone_commandline;
        DROP TABLE IF EXISTS chillzone_event;
        DROP TABLE IF EXISTS chillzone_faq;
        DROP TABLE IF EXISTS chillzone_linkto;
        DROP TABLE IF EXISTS chillzone_islocated;
        DROP TABLE IF EXISTS chillzone_log;
        DROP TABLE IF EXISTS chillzone_map;
        DROP TABLE IF EXISTS chillzone_mapfloor;
        DROP TABLE IF EXISTS chillzone_meal;
        DROP TABLE IF EXISTS chillzone_linecontent;
        DROP TABLE IF EXISTS chillzone_menu;
        DROP TABLE IF EXISTS chillzone_navigate;
        DROP TABLE IF EXISTS chillzone_network;
        DROP TABLE IF EXISTS chillzone_notificationcenter;
        DROP TABLE IF EXISTS chillzone_reservation;
        DROP TABLE IF EXISTS chillzone_locationreservation;
        DROP TABLE IF EXISTS chillzone_conflict;
        DROP TABLE IF EXISTS chillzone_tagging;
        DROP TABLE IF EXISTS chillzone_workin;
    """)

class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0004_rename_etablishment_establishment_usermeta_role_and_more'),
    ]

    operations = [
        migrations.RunPython(delete_tables, reverse_code=migrations.RunPython.noop, atomic=False),
    ]