# Generated by Django 5.1.4 on 2024-12-17 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0005_undo_migration_0005'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo_link', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_notification', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('import_link', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.category')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('In progress', 'In progress'), ('Ready', 'Ready'), ('Completed', 'Completed')], max_length=15)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('restauration_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.restaurationplace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.usermeta')),
            ],
        ),
        migrations.CreateModel(
            name='CommandComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.command')),
            ],
        ),
        migrations.CreateModel(
            name='CommandLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('command', models.ManyToManyField(related_name='command', through='chillzone.CommandComposition', to='chillzone.command')),
            ],
        ),
        migrations.AddField(
            model_name='commandcomposition',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.commandline'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.calendar')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=254)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.establishment')),
            ],
        ),
        migrations.CreateModel(
            name='LinkTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.establishment')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.restaurationplace')),
            ],
        ),
        migrations.AddField(
            model_name='establishment',
            name='restaurants',
            field=models.ManyToManyField(related_name='restaurant', through='chillzone.LinkTo', to='chillzone.restaurationplace'),
        ),
        migrations.CreateModel(
            name='IsLocated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.establishment')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.location')),
            ],
        ),
        migrations.AddField(
            model_name='establishment',
            name='locations',
            field=models.ManyToManyField(related_name='establishments', through='chillzone.IsLocated', to='chillzone.location'),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_log', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.establishment')),
            ],
        ),
        migrations.CreateModel(
            name='MapFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo_link', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.map')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='id_floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.mapfloor'),
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('starter', 'Starter'), ('main', 'Main'), ('dessert', 'Dessert'), ('side', 'Side'), ('drinks', 'Drinks'), ('other', 'Other')], max_length=10)),
                ('photo_link', models.TextField()),
                ('price', models.FloatField(default=0.0)),
                ('stock', models.IntegerField(default=0)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.category')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.restaurationplace')),
            ],
        ),
        migrations.CreateModel(
            name='LineContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.commandline')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.meal')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('photo_link', models.TextField()),
                ('price', models.FloatField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(related_name='category', through='chillzone.Associate', to='chillzone.category')),
                ('meal', models.ManyToManyField(related_name='meal', through='chillzone.LineContent', to='chillzone.meal')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.restaurationplace')),
            ],
        ),
        migrations.AddField(
            model_name='linecontent',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.menu'),
        ),
        migrations.AddField(
            model_name='commandline',
            name='menu',
            field=models.ManyToManyField(related_name='menu', through='chillzone.LineContent', to='chillzone.menu'),
        ),
        migrations.AddField(
            model_name='associate',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.menu'),
        ),
        migrations.CreateModel(
            name='Navigate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigates_as_end', to='chillzone.location')),
                ('location_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigates_as_start', to='chillzone.location')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'Youtube'), ('linkedin', 'LinkedIn'), ('workspace', 'Workspace'), ('website', 'Website')], max_length=30)),
                ('id_establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.establishment')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.usermeta')),
            ],
        ),
        migrations.AddField(
            model_name='usermeta',
            name='notification',
            field=models.ManyToManyField(related_name='notifications', through='chillzone.NotificationCenter', to='chillzone.notification'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Ongoing', 'Ongoing'), ('Pending', 'Pending')], default='Confirmed', max_length=10)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocationReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.location')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.usermeta')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.reservation')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='id_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='id_tag_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.tagcategory'),
        ),
        migrations.CreateModel(
            name='Tagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.meal')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.tag')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='tag',
            field=models.ManyToManyField(related_name='tag', through='chillzone.Tagging', to='chillzone.tag'),
        ),
        migrations.CreateModel(
            name='WorkIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.restaurationplace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='commandcomposition',
            constraint=models.UniqueConstraint(fields=('command', 'line'), name='unique_command_line'),
        ),
        migrations.AddConstraint(
            model_name='linkto',
            constraint=models.UniqueConstraint(fields=('establishment', 'restaurant'), name='unique_establishment_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='islocated',
            constraint=models.UniqueConstraint(fields=('establishment', 'location'), name='unique_establishment_location'),
        ),
        migrations.AddConstraint(
            model_name='linecontent',
            constraint=models.UniqueConstraint(fields=('menu', 'meal', 'line'), name='unique_menu_meal_line'),
        ),
        migrations.AddConstraint(
            model_name='associate',
            constraint=models.UniqueConstraint(fields=('menu', 'category'), name='unique_menu_category'),
        ),
        migrations.AddConstraint(
            model_name='navigate',
            constraint=models.UniqueConstraint(fields=('location_start', 'location_end'), name='unique_locationStart_locationEnd'),
        ),
        migrations.AddConstraint(
            model_name='notificationcenter',
            constraint=models.UniqueConstraint(fields=('user', 'notification'), name='unique_user_notification'),
        ),
        migrations.AddConstraint(
            model_name='locationreservation',
            constraint=models.UniqueConstraint(fields=('reservation', 'location'), name='unique_rervation_location'),
        ),
        migrations.AddConstraint(
            model_name='conflict',
            constraint=models.UniqueConstraint(fields=('user', 'reservation'), name='unique_user_reservation'),
        ),
        migrations.AddConstraint(
            model_name='tagging',
            constraint=models.UniqueConstraint(fields=('meal', 'tag'), name='unique_meal_tag'),
        ),
        migrations.AddConstraint(
            model_name='workin',
            constraint=models.UniqueConstraint(fields=('user', 'restaurant'), name='unique_user_restaurant'),
        ),
    ]
