# Generated by Django 5.1.4 on 2025-01-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0007_alter_command_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='id_tag',
            new_name='id_type',
        ),
    ]
