# Generated by Django 5.1.4 on 2025-01-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0008_rename_id_tag_location_id_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapfloor',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
