# Generated by Django 5.1.4 on 2025-01-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0009_mapfloor_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='qrcode_link',
            field=models.ImageField(blank=True, upload_to='qrcodes/'),
        ),
        migrations.AddField(
            model_name='location',
            name='qrcode_link',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='photo_link',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mapfloor',
            name='number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='mapfloor',
            name='photo_link',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='meal',
            name='photo_link',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='menu',
            name='photo_link',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='navigate',
            name='link_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='photo_link',
            field=models.ImageField(blank=True, default='DefaultProfile.png', upload_to=''),
        ),
    ]
