# Generated by Django 5.1.4 on 2025-01-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0010_command_qrcode_link_location_qrcode_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermeta',
            old_name='verified',
            new_name='is_verified',
        ),
        migrations.RemoveField(
            model_name='usermeta',
            name='status',
        ),
        migrations.AddField(
            model_name='usermeta',
            name='is_block',
            field=models.BooleanField(default=False),
        ),
    ]
