# Generated by Django 5.1.4 on 2025-01-26 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0011_rename_verified_usermeta_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('starter', 'Starter'), ('main', 'Main'), ('dessert', 'Dessert'), ('side', 'Side'), ('drinks', 'Drinks'), ('other', 'Other')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TypeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='associate',
            name='unique_menu_category',
        ),
        migrations.RemoveField(
            model_name='associate',
            name='category',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='type',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='category',
        ),
        migrations.AddField(
            model_name='associate',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chillzone.type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='type',
            field=models.ManyToManyField(related_name='type', through='chillzone.Associate', to='chillzone.type'),
        ),
        migrations.AddConstraint(
            model_name='associate',
            constraint=models.UniqueConstraint(fields=('menu', 'type'), name='unique_menu_type'),
        ),
        migrations.AddField(
            model_name='typecategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.category'),
        ),
        migrations.AddField(
            model_name='typecategory',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chillzone.type'),
        ),
        migrations.AddConstraint(
            model_name='typecategory',
            constraint=models.UniqueConstraint(fields=('type', 'category'), name='unique_type_category'),
        ),
    ]
