# Generated by Django 5.1.4 on 2025-01-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0012_type_typecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='menu',
            field=models.ManyToManyField(related_name='menu_id', through='chillzone.Associate', to='chillzone.menu'),
        ),
        migrations.AlterField(
            model_name='type',
            name='label',
            field=models.CharField(choices=[('starter', 'Starter'), ('main', 'Main'), ('dessert', 'Dessert'), ('side', 'Side'), ('drink', 'Drink'), ('other', 'Other')], max_length=10),
        ),
    ]
