# Generated by Django 5.1.4 on 2025-01-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0013_type_menu_alter_type_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='libelle',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='tagcategory',
            old_name='libelle',
            new_name='label',
        ),
    ]
