# Generated by Django 5.1.4 on 2025-01-27 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0014_rename_libelle_tag_label_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='associate',
            name='unique_menu_type',
        ),
        migrations.RemoveConstraint(
            model_name='typecategory',
            name='unique_type_category',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='type',
        ),
        migrations.RemoveField(
            model_name='typecategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='typecategory',
            name='type',
        ),
        migrations.AddField(
            model_name='associate',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chillzone.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typecategory',
            name='line',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='associate',
            constraint=models.UniqueConstraint(fields=('menu', 'type', 'category'), name='unique_menu_type_category'),
        ),
    ]
