# Generated by Django 5.1.4 on 2025-01-27 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0015_remove_associate_unique_menu_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypeCategory',
        ),
    ]
