# Generated by Django 5.1.4 on 2025-01-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0016_delete_typecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurationplace',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
