# Generated by Django 5.1.4 on 2025-01-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0017_restaurationplace_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeta',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
