# Generated by Django 5.1.4 on 2025-02-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0018_alter_usermeta_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='pickup_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='command',
            name='status',
            field=models.CharField(choices=[('in progress', 'In progress'), ('ready', 'Ready'), ('completed', 'Completed')], default='in progress', max_length=15),
        ),
    ]
