# Generated by Django 5.1.4 on 2025-02-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0018_alter_usermeta_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='id_establishment',
            new_name='establishment',
        ),
        migrations.AlterField(
            model_name='network',
            name='type',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('x', 'X'), ('instagram', 'Instagram'), ('youtube', 'Youtube'), ('linkedin', 'LinkedIn'), ('workspace', 'Workspace'), ('website', 'Website')], max_length=30),
        ),
    ]
