# Generated by Django 5.1.4 on 2025-02-04 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0018_alter_usermeta_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id_floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chillzone.mapfloor'),
        ),
    ]
