# Generated by Django 5.1.4 on 2025-02-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0018_alter_usermeta_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurationplace',
            name='email',
        ),
        migrations.AddField(
            model_name='restaurationplace',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
