# Generated by Django 5.1.4 on 2025-02-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0019_remove_restaurationplace_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurationplace',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
