# Generated by Django 5.1.4 on 2025-02-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0019_alter_location_id_floor'),
        ('chillzone', '0019_command_pickup_time_alter_command_status'),
        ('chillzone', '0019_rename_id_establishment_network_establishment_and_more'),
        ('chillzone', '0020_alter_restaurationplace_phone'),
    ]

    operations = [
    ]
