# Generated by Django 5.1.4 on 2025-02-11 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0021_merge_20250211_1706'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='linecontent',
            name='unique_menu_meal_line',
        ),
        migrations.RenameField(
            model_name='linecontent',
            old_name='line',
            new_name='command_line',
        ),
        migrations.RemoveField(
            model_name='commandline',
            name='command',
        ),
        migrations.RemoveField(
            model_name='commandline',
            name='menu',
        ),
        migrations.AlterField(
            model_name='linecontent',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chillzone.menu'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id_floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chillzone.mapfloor'),
        ),
        migrations.AddConstraint(
            model_name='linecontent',
            constraint=models.UniqueConstraint(fields=('menu', 'meal', 'command_line'), name='unique_menu_meal_line'),
        ),
    ]
