# Generated by Django 5.1.4 on 2025-02-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0022_remove_linecontent_unique_menu_meal_line_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='date_notification',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='description',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.RemoveField(
            model_name='usermeta',
            name='notification',
        ),
        migrations.AddField(
            model_name='calendar',
            name='reload',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='command',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='reservation',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='photo_link',
            field=models.ImageField(blank=True, null=True, upload_to='room/'),
        ),
        migrations.AlterField(
            model_name='mapfloor',
            name='photo_link',
            field=models.ImageField(blank=True, upload_to='floor/'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='photo_link',
            field=models.ImageField(blank=True, null=True, upload_to='meal/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='photo_link',
            field=models.ImageField(blank=True, null=True, upload_to='menu/'),
        ),
        migrations.AlterField(
            model_name='restaurationplace',
            name='photo_link',
            field=models.ImageField(blank=True, null=True, upload_to='restauration_place/'),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='photo_link',
            field=models.ImageField(blank=True, default='user/DefaultProfile.png', upload_to='user/'),
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
