# Generated by Django 5.1.4 on 2025-02-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0022_remove_linecontent_unique_menu_meal_line_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='import_link',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='description',
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.CharField(max_length=58, primary_key=True, serialize=False, unique=True),
        ),
    ]
