# Generated by Django 5.1.4 on 2025-02-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0022_remove_linecontent_unique_menu_meal_line_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='locationreservation',
            name='unique_rervation_location',
        ),
        migrations.AddConstraint(
            model_name='locationreservation',
            constraint=models.UniqueConstraint(fields=('location', 'day_reservation', 'start_time', 'end_time'), name='unique_location_reservation'),
        ),
    ]
