# Generated by Django 5.1.4 on 2025-02-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0023_remove_notification_date_notification_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationCenter',
        ),
    ]
