# Generated by Django 5.1.4 on 2025-02-19 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0025_remove_notification_id_notification_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Navigate',
        ),
    ]
