# Generated by Django 5.1.4 on 2025-02-19 15:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0025_alter_calendar_user_alter_event_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='reload',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
