# Generated by Django 5.1.4 on 2025-02-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0026_calendar_reload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='qrcode_link',
            field=models.ImageField(blank=True, upload_to='qrcode/'),
        ),
    ]
