# Generated by Django 5.1.4 on 2025-03-02 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0023_remove_locationreservation_unique_rervation_location_and_more'),
        ('chillzone', '0026_delete_navigate'),
        ('chillzone', '0027_alter_command_qrcode_link'),
    ]

    operations = [
    ]
