# Generated by Django 5.1.4 on 2025-03-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0028_merge_20250302_0104'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='associate',
            name='unique_menu_type_category',
        ),
        migrations.AlterField(
            model_name='calendar',
            name='reload',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='type',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('x', 'X'), ('instagram', 'Instagram'), ('youtube', 'Youtube'), ('linkedin', 'LinkedIn'), ('workspace', 'Workspace'), ('website', 'Website'), ('bluesky', 'Bluesky')], max_length=30),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Ongoing', 'Ongoing'), ('Finished', 'Finished')], default='Confirmed', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='associate',
            constraint=models.UniqueConstraint(fields=('id', 'menu', 'type', 'category'), name='unique_menu_type_category'),
        ),
    ]
