# Generated by Django 5.1.4 on 2025-03-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0029_remove_associate_unique_menu_type_category_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='associate',
            name='unique_menu_type_category',
        ),
        migrations.AddConstraint(
            model_name='associate',
            constraint=models.UniqueConstraint(fields=('menu', 'type', 'category'), name='unique_menu_type_category'),
        ),
    ]
