# Generated by Django 5.1.4 on 2025-03-05 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chillzone', '0030_remove_associate_unique_menu_type_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='qrcode_link',
        ),
    ]
