services:
    web:
      image: api_chillzone:beta1
      #build: .
      volumes:
        - /docker/chillzone_api/api/:/api/chillzone
      ports:
        - "3000:3000"
      # environment:
      #   - DEBUG=True