export enum ROUTE {
  LOGIN_SCREEN = 'LoginScreen',
  FORGOT_PASSWORD = 'ForgotPasswordScreen',
  FORGOT_MDP = 'ForgotMdpScreen',
  RESET_PASSWORD = 'ResetPasswordScreen',
  NOTIFICATION = 'NotificationScreen',
  HOME = 'HomeScreen',
  RESTAURATION = 'RestaurationScreen',
  FAQ = 'FaqScreen',
  PAYMENT = 'PaymentScreen',
  DISPENSER = 'DispenserScreen',
  DISPENSER_MODAL = 'DispenserModal',
  FINAL_PAYMENT = 'FinalPaymentScreen',
  RESERVATION = 'ReservationScreen',
  ACCOUNT = 'AccountScreen',
  LINKS = 'LinksScreen',
  MENU_MODAL = 'MenuModal',
  RESERVATION_SUMMARY = 'ReservationSummaryScreen',
  CART = 'CartScreen',
  ALERT = 'AlertScreen',
  COMMAND_SUMMARY = 'CommandSummaryScreen',
  CALENDAR = 'CalendarScreen',
  NAVIGATION = 'NavigationScreen',
  AR_NAVIGATION = 'ARNavigationScreen',
}
